version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test1
      MYSQL_ROOT_PASSWORD: test1
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d